version: "3.9"

services:
  server:
    container_name: ticket-to-ride-server
    image: ticket-to-ride-server
    environment:
        SERVER_PORT: ${SERVER_PORT}
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: .
      dockerfile: packages/server/Dockerfile.prod
      args:
        SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    networks:
      - awesome
  postgres:
    container_name: ticket-to-ride-postgres
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
