export enum ROUTES {
  root = '/',
  about = '/about',
  rating = '/rating',
  signIn = '/sign-in',
  signUp = '/sign-up',
  startGame = '/',
  endGame = '/end-game',
  game = '/game',
  arcade = '/arcade',
  forum = '/forum',
  themeNew = '/theme/new',
  themeDetail = '/theme/:id',
  themeEdit = '/theme/:id/edit',
  profile = '/profile',
  error = '/error/:code',
}
